google_search:
  resources_servers:
    google_search:
      entrypoint: app.py
      domain: agent
      verified: false
      description: Multi-choice question answering problems with search tools integrated
      value: Improve knowledge-related benchmarks with search tools
      dataset_name: Nemotron-RL-knowledge-web_search-mcqa
google_search_simple_agent:
  responses_api_agents:
    simple_agent:
      entrypoint: app.py
      resources_server:
        type: resources_servers
        name: google_search
      model_server:
        type: responses_api_models
        name: policy_model
      datasets:
      - name: train
        type: train
        jsonl_fpath: resources_servers/google_search/data/train.jsonl
        gitlab_identifier:
          dataset_name: search_STEM_syn_gpqa_v1_2_difficulty_filtered
          version: 0.0.1
          artifact_fpath: MCQA_syn_gpqa_1_2_difficulty_filtered_responses_api.jsonl
        license: Apache 2.0
      - name: example
        type: example
        jsonl_fpath: resources_servers/google_search/data/example.jsonl
