instruction_following:
  resources_servers:
    instruction_following:
      entrypoint: app.py
      domain: instruction_following
      verified: false
      description: Instruction following datasets targeting IFEval and IFBench style instruction following capabilities
      value: Improve IFEval and IFBench
      dataset_name: Nemotron-RL-instruction_following
instruction_following_simple_agent:
  responses_api_agents:
    simple_agent:
      entrypoint: app.py
      resources_server:
        type: resources_servers
        name: instruction_following
      model_server:
        type: responses_api_models
        name: policy_model
      datasets:
      - name: train
        type: train
        jsonl_fpath: resources_servers/instruction_following/data/train.jsonl
        gitlab_identifier:
          dataset_name: instruction_following
          version: 0.0.1
          artifact_fpath: instruction_following.jsonl
        license: Apache 2.0
      - name: example
        type: example
        jsonl_fpath: resources_servers/instruction_following/data/example.jsonl
